### PR TITLE
Update unix.rs

### PR DESCRIPTION
**Pull request by rakshith-ravi**
I haven't tested this yet. Just a proposal of what I think might be the fix

### CODE REVIEW

**Comment by brunoczim** [comment]
Hmm yes, your proposal looks good, but it still fails to compile.
```
error[E0308]: mismatched types
   --> src/unix.rs:228:23
    |
228 |         Ok(OsString { alloc, len })
    |                       ^^^^^ expected `u8`, found `i8`
    |
    = note: expected struct `std::ptr::NonNull<u8>`
               found struct `std::ptr::NonNull<i8>`

error[E0308]: mismatched types
   --> src/unix.rs:275:38
    |
275 |     Ok(EitherOsStr::Owned(OsString { alloc, len: slice.len() }))
    |                                      ^^^^^ expected `u8`, found `i8`
    |
    = note: expected struct `std::ptr::NonNull<u8>`
               found struct `std::ptr::NonNull<i8>`

error: aborting due to 2 previous errors
```

I think instead of defining the whole struct using a #[cfg], we could just define it using `libc::c_char`, which is the type that libc uses for C strings:
```
PS: `libc::c_char` is defined as `u8` on arm.

**Review by brunoczim — CHANGES_REQUESTED** [review]
Well, I would suggest reverting it, and then replace every `i8` by `libc::c_char`.

**Review by brunoczim — APPROVED** [review]
Sorry, I wanted to show the changes I was proposing and I ended up commiting them grr. I will merge the PR anyways hahaha.

**Comment by rakshith-ravi** [comment]
No problem haha. I'm just happy to make this a better library to use :P

Thanks for merging it. Would you happen to be able to release it as well? Or is there a CI system that does it automatically?

**Comment by brunoczim** [comment]
I have released it a few minutes after the merge. And no, there is no CI for now, I have to learn GH tools for CI like travis, I am used to GitLab CI haha.

**Comment by rakshith-ravi** [comment]
Haha alright. Thanks a lot

**Pull request merged**
